version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i -g yarn --unsafe-perm
      - npm i -g serverless@3.9.2 --unsafe-perm
  build:
    commands:
      - cd ./dashboard/client/ && ./publish