#!/bin/python

import os
import ssl
from http.server import HTTPServer
from dotenv import load_dotenv
from dashboard.server.handler import ServerHandler

if __name__ == '__main__':

    load_dotenv()
    API_URL = os.getenv('API_URL')
    API_PORT = int(os.getenv('API_PORT'))
    CERT_FILE = os.getenv('CERT_FILE')

    server = HTTPServer(
        (API_URL, API_PORT),
        ServerHandler
    )
    server.socket = ssl.wrap_socket(
        server.socket,
        server_side=True,
        certfile=CERT_FILE,
        ssl_version=ssl.PROTOCOL_TLSv1_2
    )
    print(f'Server started on {API_URL}:{API_PORT}.')

    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass

    server.server_close()
    print('Server shutdown.')