#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

sudo gnome-terminal --working-directory="$dir/" -- ./run ./dashboard-server
sudo gnome-terminal --working-directory="$dir/dashboard/client/" -- npm run start
