#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

gnome-terminal --working-directory="$dir/" -- ./run ./dashboard-server
gnome-terminal --working-directory="$dir/dashboard/client/" -- npm run start
