#!/bin/bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

gnome-terminal --tab --working-directory="$dir/" -- sudo ./run ./dashboard-server && \
gnome-terminal --tab --working-directory="$dir/dashboard/client/" -- npm run start
