#!/bin/python

import os
from dotenv import load_dotenv
from bot import Bot

load_dotenv()
API_TOKEN = os.getenv('DISCORD_TOKEN')
DATA_DIR = os.getenv('DATA_DIR')

bot = Bot()
bot.load(DATA_DIR)
bot.run(API_TOKEN)