const ActionTypes = {
    GET_PERSONAS: 'GET_PERSONAS',
    RECEIVE_PERSONAS: 'RECEIVE_PERSONAS',
    PUT_PERSONA: 'PUT_PERSONA',
    REMOVE_PERSONA: 'REMOVE_PERSONA',
    GET_REACTIONS: 'GET_REACTIONS',
    RECEIVE_REACTIONS: 'RECEIVE_REACTIONS',
    PUT_REACTION: 'PUT_REACTION',
    REMOVE_REACTION: 'REMOVE_REACTION'
}

export default ActionTypes;